// <auto-generated />
using System;
using KeePark.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KeePark.Migrations.KeePark
{
    [DbContext(typeof(KeeParkContext))]
    [Migration("20191010204205_newContext")]
    partial class newContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KeePark.Models.ParkingSpot", b =>
                {
                    b.Property<Guid>("ParkingSpotID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<int>("NunOfOrders");

                    b.Property<string>("OwnerID");

                    b.Property<int>("Price");

                    b.Property<string>("SpotDescription");

                    b.Property<string>("SpotName")
                        .IsRequired();

                    b.Property<string>("filePath");

                    b.HasKey("ParkingSpotID");

                    b.ToTable("ParkingSpot");
                });
#pragma warning restore 612, 618
        }
    }
}
